name: Run Library Bot Daily

on:
  schedule:
    # 每天 UTC 時間的 21:00 執行 (對應台灣時間早上 5:00)
    # Cron 語法：分鐘 小時 日 月 星期
    # UTC 21:00 = CST (Asia/Taipei, UTC+8) 05:00 AM
    - cron: '0 21 * * *'
  workflow_dispatch: # 允許手動觸發 (方便測試)

jobs:
  run-script:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu runner
    
    # 設定 job 層級的超時時間，例如 10 分鐘，防止腳本卡住過久
    timeout-minutes: 10 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # 使用 v4 版本

    - name: Set up Python
      uses: actions/setup-python@v5 # 使用 v5 版本
      with:
        python-version: '3.9' # 或者你 Colab 中使用的 Python 版本，例如 '3.10', '3.11'

    - name: Install system dependencies (Tesseract OCR and Chromium/ChromeDriver)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y tesseract-ocr chromium-chromedriver
        # 確保 chromedriver 在 PATH 中 (如果需要，通常 Service() 會自動處理)
        # 如果後續報錯找不到 chromedriver，可以取消註解下面這行，並確認路徑
        # sudo ln -s -f /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

    - name: Upgrade pip and Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # 直接安裝，如果 requirements.txt 不存在或為空，pip 會報錯，這樣更容易發現問題
        python -m pip install -r requirements.txt
        # 為了調試，可以列出已安裝的套件
        python -m pip freeze 

    - name: Run Python script
      env:
        LIBRARY_CARD_NUMBER: ${{ secrets.LIBRARY_CARD_NUMBER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        # 如果你的 Python 腳本需要明確知道 ChromeDriver 的路徑（雖然通常不需要）
        # CHROMEDRIVER_PATH: /usr/lib/chromium-browser/chromedriver 
      run: python 圖書館.py # 確認這是你的 Python 腳本檔名
